CC=$(CROSS_PREFIX)gcc
AR=$(CROSS_PREFIX)ar
LIBETHER=libether.a
LIBETHER_DIR=$(PWD)

TARGET_LIB_DIR = $(LIBETHER_DIR)/_built/lib
TARGET_INCLUDE_DIR = $(LIBETHER)/_built/include
ENABLE_TESTS_COVERAGE = true
DISABLE_CPPCHECK = true
